"use client";

// import type { Metadata } from "next";
import { Inter, Syne } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [scriptLoaded, setScriptLoaded] = useState(false);

  useEffect(() => {
    const script = document.createElement('script');
    if (!scriptLoaded) {
      script.src = 'https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';
      script.async = true;
      document.body.appendChild(script);
      setScriptLoaded(true);
    }
    return () => {
      document.body.removeChild(script);
    };
  }, [scriptLoaded]);

  return (
    <html lang="en">
      <head>
      <script
          dangerouslySetInnerHTML={{
            __html: `
              function googleTranslateElementInit() {
                new google.translate.TranslateElement(
                  { pageLanguage: 'en',
                  autoDisplay: false
                   },
                  'google_translate_element'
                );
              }
            `,
          }}
        />
      </head>
      <body style={{ fontFamily: "Syne" }} className={inter.className}>
        {children}
      </body>
    </html>
  );
}